# version: "3.9"

services:
  certbot:
    container_name: certbot
    entrypoint: [ "/bin/sh" ]
    # image: certbot/certbot:latest # for manual plugin
    image: certbot/dns-cloudflare:latest # for DNS plugin
    network_mode: "bridge"
    restart: unless-stopped
    tty: true
    volumes:
      - ./plugin/cloudflare.ini:$HOME/.secrets/certbot/cloudflare.ini # for DNS plugin, manual plugin ought to comment this line
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
